# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fwuensch <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/07/15 19:04:42 by fwuensch          #+#    #+#              #
#    Updated: 2017/07/16 19:42:09 by fwuensch         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	gcc -Wall -Wextra -Werror main.c ft_putchar.c rush00.c -o rush-00
	gcc -Wall -Wextra -Werror main.c ft_putchar.c rush01.c -o rush-01
	gcc -Wall -Wextra -Werror main.c ft_putchar.c rush02.c -o rush-02
	gcc -Wall -Wextra -Werror main.c ft_putchar.c rush03.c -o rush-03
	gcc -Wall -Wextra -Werror main.c ft_putchar.c rush04.c -o rush-04

clean:
	rm -f rush-00 rush-01 rush-02 rush-03 rush-04

fclean: clean

re: clean all
